apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-app-ingress
  namespace: learning
spec:
  rules:
    - host: myfirstapp.com
      http:
        paths:
          - backend:
              serviceName: spring-app-svc
              servicePort: 5001
            path: /
            pathType: ImplementationSpecific