name: test workflow

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: true
        description: your name

jobs:
  learn-script:
    runs-on: ubuntu-latest
    outputs:
      out-name: ${{steps.first.outputs.my-name}}
    steps:
      - name: learn step 1
        id: first
        run: echo "my-name=${{inputs.name}}" >> $GITHUB_OUTPUT
        shell: sh
      - name: learn step 2
        id: second
        run: echo '${{steps.first.outputs.my-name}}'
        shell: sh
        
  print-output:
    runs-on: ubuntu-latest
    needs: learn-script
    steps:
      - name: print step 1
        id: print
        run: echo "${{needs.learn-script.outputs.out-name}}"
        shell: sh
